// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prototipo1.Data;

#nullable disable

namespace Prototipo1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251007024335_addProyectoToFactura")]
    partial class addProyectoToFactura
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prototipo1.Models.Factura", b =>
                {
                    b.Property<int>("IdFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFactura"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoFactura")
                        .HasColumnType("int");

                    b.HasKey("IdFactura");

                    b.HasIndex("IdProyecto");

                    b.HasIndex("IdTipoFactura");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("Prototipo1.Models.FacturaProducto", b =>
                {
                    b.Property<int>("IdFacturaProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFacturaProducto"));

                    b.Property<int>("CantidadAumentada")
                        .HasColumnType("int");

                    b.Property<string>("EntregadoA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFactura")
                        .HasColumnType("int");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdFacturaProducto");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdProducto");

                    b.ToTable("FacturaProducto");
                });

            modelBuilder.Entity("Prototipo1.Models.Familia", b =>
                {
                    b.Property<int>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamilia"));

                    b.Property<string>("NombreFamilia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdFamilia");

                    b.ToTable("Familia");

                    b.HasData(
                        new
                        {
                            IdFamilia = 1,
                            NombreFamilia = "BAÑOS"
                        },
                        new
                        {
                            IdFamilia = 2,
                            NombreFamilia = "BASES"
                        },
                        new
                        {
                            IdFamilia = 3,
                            NombreFamilia = "MADERAS"
                        },
                        new
                        {
                            IdFamilia = 4,
                            NombreFamilia = "PAREDES"
                        },
                        new
                        {
                            IdFamilia = 5,
                            NombreFamilia = "PAREDES Y PISO"
                        },
                        new
                        {
                            IdFamilia = 6,
                            NombreFamilia = "PARQUEO"
                        },
                        new
                        {
                            IdFamilia = 7,
                            NombreFamilia = "SEGURIDAD"
                        },
                        new
                        {
                            IdFamilia = 8,
                            NombreFamilia = "SOPORTE"
                        },
                        new
                        {
                            IdFamilia = 9,
                            NombreFamilia = "SUELOS"
                        },
                        new
                        {
                            IdFamilia = 10,
                            NombreFamilia = "VARIOS"
                        },
                        new
                        {
                            IdFamilia = 11,
                            NombreFamilia = "Vidrios"
                        },
                        new
                        {
                            IdFamilia = 12,
                            NombreFamilia = "PUERTAS "
                        });
                });

            modelBuilder.Entity("Prototipo1.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInventario"));

                    b.Property<double>("Existencias")
                        .HasColumnType("float");

                    b.Property<int>("IdProducto")
                        .HasColumnType("int");

                    b.HasKey("IdInventario");

                    b.HasIndex("IdProducto");

                    b.ToTable("Inventario");
                });

            modelBuilder.Entity("Prototipo1.Models.Nivel", b =>
                {
                    b.Property<int>("IdNivel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNivel"));

                    b.Property<int>("IdProyecto")
                        .HasColumnType("int");

                    b.Property<string>("NombreNivel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdNivel");

                    b.HasIndex("IdProyecto");

                    b.ToTable("Nivel");
                });

            modelBuilder.Entity("Prototipo1.Models.Producto", b =>
                {
                    b.Property<int>("IdProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProducto"));

                    b.Property<string>("CodigoProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdFamilia")
                        .HasColumnType("int");

                    b.Property<int>("IdUnidad")
                        .HasColumnType("int");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MediaArtimetica")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProducto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProducto");

                    b.HasIndex("CodigoProducto")
                        .IsUnique();

                    b.HasIndex("IdFamilia");

                    b.HasIndex("IdUnidad");

                    b.ToTable("Producto");
                });

            modelBuilder.Entity("Prototipo1.Models.Proyecto", b =>
                {
                    b.Property<int>("IdProyecto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProyecto"));

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NombreProyecto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdProyecto");

                    b.ToTable("Proyecto");
                });

            modelBuilder.Entity("Prototipo1.Models.TipoFactura", b =>
                {
                    b.Property<int>("IdTipoFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTipoFactura"));

                    b.Property<string>("NombreTipoFactura")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTipoFactura");

                    b.ToTable("TipoFactura");

                    b.HasData(
                        new
                        {
                            IdTipoFactura = 1,
                            NombreTipoFactura = "Entrada"
                        },
                        new
                        {
                            IdTipoFactura = 2,
                            NombreTipoFactura = "Salida"
                        });
                });

            modelBuilder.Entity("Prototipo1.Models.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdUnidad");

                    b.ToTable("Unidad");

                    b.HasData(
                        new
                        {
                            IdUnidad = 1,
                            NombreUnidad = "BOLSA"
                        },
                        new
                        {
                            IdUnidad = 2,
                            NombreUnidad = "CUBETA"
                        },
                        new
                        {
                            IdUnidad = 3,
                            NombreUnidad = "M²"
                        },
                        new
                        {
                            IdUnidad = 4,
                            NombreUnidad = "PIEZA"
                        },
                        new
                        {
                            IdUnidad = 5,
                            NombreUnidad = "UNIDAD"
                        });
                });

            modelBuilder.Entity("Prototipo1.Models.Factura", b =>
                {
                    b.HasOne("Prototipo1.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prototipo1.Models.TipoFactura", "TipoFactura")
                        .WithMany()
                        .HasForeignKey("IdTipoFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");

                    b.Navigation("TipoFactura");
                });

            modelBuilder.Entity("Prototipo1.Models.FacturaProducto", b =>
                {
                    b.HasOne("Prototipo1.Models.Factura", "Factura")
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prototipo1.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Prototipo1.Models.Inventario", b =>
                {
                    b.HasOne("Prototipo1.Models.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("IdProducto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("Prototipo1.Models.Nivel", b =>
                {
                    b.HasOne("Prototipo1.Models.Proyecto", "Proyecto")
                        .WithMany()
                        .HasForeignKey("IdProyecto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proyecto");
                });

            modelBuilder.Entity("Prototipo1.Models.Producto", b =>
                {
                    b.HasOne("Prototipo1.Models.Familia", "Familia")
                        .WithMany()
                        .HasForeignKey("IdFamilia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Prototipo1.Models.Unidad", "Unidad")
                        .WithMany()
                        .HasForeignKey("IdUnidad")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Familia");

                    b.Navigation("Unidad");
                });
#pragma warning restore 612, 618
        }
    }
}
