// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Prototipo1.Data;

#nullable disable

namespace Prototipo1.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20250821071640_agregarUnidad")]
    partial class agregarUnidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Prototipo1.Models.Familia", b =>
                {
                    b.Property<int>("IdFamilia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdFamilia"));

                    b.Property<string>("NombreFamilia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdFamilia");

                    b.ToTable("Familia");

                    b.HasData(
                        new
                        {
                            IdFamilia = 1,
                            NombreFamilia = "BAÑOS"
                        },
                        new
                        {
                            IdFamilia = 2,
                            NombreFamilia = "BASES"
                        },
                        new
                        {
                            IdFamilia = 3,
                            NombreFamilia = "MADERAS"
                        },
                        new
                        {
                            IdFamilia = 4,
                            NombreFamilia = "PAREDES"
                        },
                        new
                        {
                            IdFamilia = 5,
                            NombreFamilia = "PAREDES Y PISO"
                        },
                        new
                        {
                            IdFamilia = 6,
                            NombreFamilia = "PARQUEO"
                        },
                        new
                        {
                            IdFamilia = 7,
                            NombreFamilia = "SEGURIDAD"
                        },
                        new
                        {
                            IdFamilia = 8,
                            NombreFamilia = "SOPORTE"
                        },
                        new
                        {
                            IdFamilia = 9,
                            NombreFamilia = "SUELOS"
                        },
                        new
                        {
                            IdFamilia = 10,
                            NombreFamilia = "VARIOS"
                        },
                        new
                        {
                            IdFamilia = 11,
                            NombreFamilia = "Vidrios"
                        },
                        new
                        {
                            IdFamilia = 12,
                            NombreFamilia = "PUERTAS "
                        });
                });

            modelBuilder.Entity("Prototipo1.Models.Unidad", b =>
                {
                    b.Property<int>("IdUnidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUnidad"));

                    b.Property<string>("NombreUnidad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IdUnidad");

                    b.ToTable("Unidad");

                    b.HasData(
                        new
                        {
                            IdUnidad = 1,
                            NombreUnidad = "BOLSA"
                        },
                        new
                        {
                            IdUnidad = 2,
                            NombreUnidad = "CUBETA"
                        },
                        new
                        {
                            IdUnidad = 3,
                            NombreUnidad = "M²"
                        },
                        new
                        {
                            IdUnidad = 4,
                            NombreUnidad = "PIEZA"
                        },
                        new
                        {
                            IdUnidad = 5,
                            NombreUnidad = "UNIDAD"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
